name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'  # or 'zulu', 'temurin', etc.
          java-package: 'jdk'
          architecture: 'x64'

      - name: Init gradle wrapper
        run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle wrapper
        run: ./gradlew build
